export const ACTION_TYPES = {
  INIT_CUSTOMER_ID: 'INIT_CUSTOMER_ID',
  INIT_CART: 'INIT_CART',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  INIT_WISH_LIST: 'INIT_WISH_LIST',
  ADD_WISH_LIST_ITEM: 'ADD_WISH_LIST_ITEM',
  REMOVE_WISH_LIST_ITEM: 'REMOVE_WISH_LIST_ITEM',
  AUTH_CUSTOMER: 'AUTH_CUSTOMER',
  REGISTER_CUSTOMER: 'REGISTER_CUSTOMER',
  CREATE_ORDER: 'CREATE_ORDER',
};
